### ISSUE TITLE
[k8s] Implement ipv4/ipv6 kubenet dual-stack feature-gate

### ISSUE THREAD

**Issue by lachie83** [Azure/container-compute-upstream#17]

**Comment by bridgetkromhout** [comment]
https://docs.microsoft.com/en-us/azure/aks/configure-kubenet-dual-stack?tabs=azure-cli%2Ckubectl

"AKS clusters can now be deployed in a dual-stack (using both IPv4 and IPv6 addresses) mode when using [kubenet](https://docs.microsoft.com/en-us/azure/aks/configure-kubenet) networking and a dual-stack Azure virtual network."

**Comment by bridgetkromhout** [comment]
Closing per @khenidak as complete.
