### ISSUE TITLE
[k8s] Update e2e test infra for cloud-provider-azure prow jobs

### ISSUE THREAD

**Issue by ritazh** [Azure/container-compute-upstream#19]
https://github.com/kubernetes/cloud-provider-azure/issues/4

**Comment by craiglpeters** [comment]
[Internal Doc](https://microsoft.sharepoint.com/:w:/t/azurecontainercompute/EeO1kj5v53ZJqTtdZMz2QZEBbbSx6iA06GQPxPsvQDPGig?e=GzsUVX)

**Comment by ritazh** [comment]
Waiting on test-infra upstream to publish a new version of `kubekins-e2e` image that includes all of our recent updates to kubetest to support building and test cloud controller manager. Once it's published, we will update the existing cloud-provider-azure prow job config yamls.
