### ISSUE TITLE
Test kubenet for Windows containers in Kubernetes

### ISSUE THREAD

**Issue by craiglpeters** [Azure/container-compute-upstream#39]
In addition to the Azure-CNI support for Advanced networking in AKS, Windows containers need to support kubenetI for basic networking.

TODO: document definition of done
TODO: Link to issue for aks-engine implementation and testing

**Comment by PatrickLang** [comment]
This is working and tested in the AKS-Engine jenkins setup. I don't think there's any work left to do, AKS could vendor this code in if they want to release it.
