### ISSUE TITLE
cluster-autoscaler redesign

### ISSUE THREAD

**Issue by mboersma** [Azure/container-compute-upstream#41]
- collect any existing documents or ideas for redesign of the Azure cloudprovider in cluster-autoscaler (or larger scope?)
- coalesce this into a set of goals ranked by priority we can implement

Please help me clarify this issue!

**Comment by feiskyer** [comment]
@mboersma any contexts on redesign?

**Comment by mboersma** [comment]
@lachie83 had mentioned once that there was a doc or some ideas for CA redesign, and @ritazh encouraged me to create an issue so we don't forget about it. So...I've got nothing yet, but I'm hoping we can use this issue to do some discussion.

**Comment by mboersma** [comment]
@lachie83 was there any meat for these bones that you're aware of? 🤞
