### ISSUE TITLE
Review and update Gatekeeper documentation on OPA Website

### ISSUE THREAD

**Issue by craiglpeters** [Azure/container-compute-upstream#78]
https://www.openpolicyagent.org/docs/edge/kubernetes-introduction/

based on 
https://kubernetes.io/blog/2019/08/06/opa-gatekeeper-policy-and-governance-for-kubernetes/

**Comment by prary** [comment]
Are you still working on it? If not then allow me to fix it and raise the PR.
Yamls need to updated immediately, personally have wasted entire day running the outdated yaml.

Present gatekeeper requires violation block instead of deny block in rego file.
