### ISSUE TITLE
[SMI] Traffic Metrics to beta milestone

### ISSUE THREAD

**Issue by michelleN** [Azure/container-compute-upstream#82]
We need to figure out what it'll take to get Traffic Metrics part of SMI to "beta" meaning all stakeholders agree that what we have is good, stable, tested and ready for v1.0.0 of the SMI spec.  I'm going through the issue queue and taking the Istio Metrics implementation for a spin to fill out the [metrics project board](https://github.com/deislabs/smi-spec/projects/1).

**Comment by bridgetkromhout** [comment]
Thanks! We can close this issue now, as such topics should be handled in https://github.com/servicemeshinterface/smi-spec.
