### ISSUE TITLE
[k8s] Implement ipv4/ipv6 PodIP changes

### ISSUE THREAD

**Issue by khenidak** [Azure/container-compute-upstream#9]
PR: https://github.com/kubernetes/kubernetes/pull/73977

**Comment by lachie83** [comment]
Splitting this into smaller pieces.

**Comment by bridgetkromhout** [comment]
Dual-stack is [stable/GA as of Kubernetes 1.23](https://kubernetes.io/blog/2021/12/08/dual-stack-networking-ga/). Thanks!
